version: '3.8'

services:

  server:
    image: galleria-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/galleria_db?schema=public
      - REDIS_URL=redis://redis:6379
    container_name: galleria-backend-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-galleria
    ports:
      - '6500:5432'
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
    environment:
      # POSTGRES_HOST: 127.0.0.1
      # POSTGRES_PORT: 6500
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data

volumes:
  postgresDB:
  redis_data:

