version: '3.9'

services:

  dbtest:
    image: postgres:latest
    env_file: .env.test
    restart: always
    container_name: galleria-db-test
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: galleria_tests

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
#     volumes:
#       - ./redis_data:/data

# volumes:
#   postgresDB:
#   redis_data:

