version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-galleria
    ports:
      - '6500:5432'
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
    environment:
      # POSTGRES_HOST: 127.0.0.1
      # POSTGRES_PORT: 6500
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgresDB:

