version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-galleria
    ports:
      - '6500:5432'
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 6500
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: galleria_db

volumes:
  postgresDB:

